-- CENSO DIRECTO v2 (escape BigQuery para apostrofos): un solo escaneo de
-- ~907.66 GB del GKG filtrado a ECON_STOCKMARKET, cruzado con los 1,012
-- tickers y agregado a serie diaria. Correr UNA vez.
WITH entidades AS (
  SELECT * FROM UNNEST([
    STRUCT('GME' AS ticker, 'gamestop' AS nombre),
    STRUCT('AMC' AS ticker, 'amc entertainment' AS nombre),
    STRUCT('TSLA' AS ticker, 'tesla' AS nombre),
    STRUCT('RDDT' AS ticker, 'reddit' AS nombre),
    STRUCT('NVDA' AS ticker, 'nvidia' AS nombre),
    STRUCT('AAPL' AS ticker, 'apple' AS nombre),
    STRUCT('TWTR' AS ticker, 'twitter' AS nombre),
    STRUCT('NOK' AS ticker, 'nokia' AS nombre),
    STRUCT('PLTR' AS ticker, 'palantir' AS nombre),
    STRUCT('MSFT' AS ticker, 'microsoft' AS nombre),
    STRUCT('AMD' AS ticker, 'advanced micro devices' AS nombre),
    STRUCT('BBBY' AS ticker, 'bed bath & beyond' AS nombre),
    STRUCT('INTC' AS ticker, 'intel' AS nombre),
    STRUCT('NFLX' AS ticker, 'netflix' AS nombre),
    STRUCT('HOOD' AS ticker, 'robinhood' AS nombre),
    STRUCT('SPCE' AS ticker, 'virgin galactic' AS nombre),
    STRUCT('SNDL' AS ticker, 'sundial growers' AS nombre),
    STRUCT('SNDL' AS ticker, 'sndl' AS nombre),
    STRUCT('NIO' AS ticker, 'nio' AS nombre),
    STRUCT('RKT' AS ticker, 'rocket companies' AS nombre),
    STRUCT('BABA' AS ticker, 'alibaba' AS nombre),
    STRUCT('AMZN' AS ticker, 'amazon' AS nombre),
    STRUCT('BB' AS ticker, 'blackberry' AS nombre),
    STRUCT('TLRY' AS ticker, 'tilray' AS nombre),
    STRUCT('NKLA' AS ticker, 'nikola' AS nombre),
    STRUCT('WMT' AS ticker, 'walmart' AS nombre),
    STRUCT('CLOV' AS ticker, 'clover health investments' AS nombre),
    STRUCT('PYPL' AS ticker, 'paypal' AS nombre),
    STRUCT('CLNE' AS ticker, 'clean energy fuels' AS nombre),
    STRUCT('DIS' AS ticker, 'disney' AS nombre),
    STRUCT('SMCI' AS ticker, 'super micro computer' AS nombre),
    STRUCT('META' AS ticker, 'meta platforms' AS nombre),
    STRUCT('MVIS' AS ticker, 'microvision' AS nombre),
    STRUCT('BA' AS ticker, 'boeing' AS nombre),
    STRUCT('GOOG' AS ticker, 'alphabet' AS nombre),
    STRUCT('ATER' AS ticker, 'aterian' AS nombre),
    STRUCT('WISH' AS ticker, 'contextlogic' AS nombre),
    STRUCT('MSTR' AS ticker, 'microstrategy' AS nombre),
    STRUCT('ASTS' AS ticker, 'ast spacemobile' AS nombre),
    STRUCT('NAKD' AS ticker, 'naked brand' AS nombre),
    STRUCT('PROG' AS ticker, 'progenity' AS nombre),
    STRUCT('CLF' AS ticker, 'cleveland cliffs' AS nombre),
    STRUCT('COIN' AS ticker, 'coinbase' AS nombre),
    STRUCT('WKHS' AS ticker, 'workhorse' AS nombre),
    STRUCT('GOOGL' AS ticker, 'alphabet' AS nombre),
    STRUCT('APHA' AS ticker, 'aphria' AS nombre),
    STRUCT('DKNG' AS ticker, 'draftkings' AS nombre),
    STRUCT('DJT' AS ticker, 'trump media' AS nombre),
    STRUCT('BYND' AS ticker, 'beyond meat' AS nombre),
    STRUCT('CRSR' AS ticker, 'corsair gaming' AS nombre),
    STRUCT('UNH' AS ticker, 'unitedhealth' AS nombre),
    STRUCT('PUMP' AS ticker, 'propetro' AS nombre),
    STRUCT('CHWY' AS ticker, 'chewy' AS nombre),
    STRUCT('RKLB' AS ticker, 'rocket lab usa' AS nombre),
    STRUCT('SNAP' AS ticker, 'snapchat' AS nombre),
    STRUCT('ORCL' AS ticker, 'oracle' AS nombre),
    STRUCT('WEN' AS ticker, 'wendys' AS nombre),
    STRUCT('MRNA' AS ticker, 'moderna' AS nombre),
    STRUCT('BBIG' AS ticker, 'vinco ventures' AS nombre),
    STRUCT('CVNA' AS ticker, 'carvana' AS nombre),
    STRUCT('PFE' AS ticker, 'pfizer' AS nombre),
    STRUCT('MGM' AS ticker, 'm g m resorts international' AS nombre),
    STRUCT('MGM' AS ticker, 'mgm resorts international' AS nombre),
    STRUCT('PXD' AS ticker, 'pioneer natural resources' AS nombre),
    STRUCT('ASPC' AS ticker, 'spac iii acquisition corp.' AS nombre),
    STRUCT('DWAC' AS ticker, 'digital world acquisition' AS nombre),
    STRUCT('BLK' AS ticker, 'blackrock' AS nombre),
    STRUCT('MP' AS ticker, 'm p materials' AS nombre),
    STRUCT('MP' AS ticker, 'mp materials' AS nombre),
    STRUCT('CCIV' AS ticker, 'churchill capital iv' AS nombre),
    STRUCT('FSII' AS ticker, 'f s development ii' AS nombre),
    STRUCT('FSII' AS ticker, 'fs development ii' AS nombre),
    STRUCT('AVGO' AS ticker, 'broadcom' AS nombre),
    STRUCT('VBIV' AS ticker, 'vbi vaccines' AS nombre),
    STRUCT('SDC' AS ticker, 'smiledirectclub' AS nombre),
    STRUCT('NAV' AS ticker, 'navistar international' AS nombre),
    STRUCT('BRK' AS ticker, 'berkshire hathaway' AS nombre),
    STRUCT('TSM' AS ticker, 'taiwan semiconductor mfg' AS nombre),
    STRUCT('CRM' AS ticker, 'salesforce' AS nombre),
    STRUCT('CRM' AS ticker, 'crm' AS nombre),
    STRUCT('UPC' AS ticker, 'universe pharmaceuticals' AS nombre),
    STRUCT('PTON' AS ticker, 'peloton interactive' AS nombre),
    STRUCT('TCBI' AS ticker, 'texas capital bancshares' AS nombre),
    STRUCT('JPM' AS ticker, 'jpmorgan chase &' AS nombre),
    STRUCT('UEC' AS ticker, 'uranium energy' AS nombre),
    STRUCT('FRC' AS ticker, 'first republic bank' AS nombre),
    STRUCT('FRC' AS ticker, 'first republic' AS nombre),
    STRUCT('HTZ' AS ticker, 'hertz global' AS nombre),
    STRUCT('UWMC' AS ticker, 'uwm holdings' AS nombre),
    STRUCT('UWMC' AS ticker, 'united wholesale mortgage' AS nombre),
    STRUCT('GOEV' AS ticker, 'canoo' AS nombre),
    STRUCT('SBUX' AS ticker, 'starbucks' AS nombre),
    STRUCT('RIDE' AS ticker, 'lordstown motors' AS nombre),
    STRUCT('CRWD' AS ticker, 'crowdstrike' AS nombre),
    STRUCT('SPRT' AS ticker, 'support.com' AS nombre),
    STRUCT('SPRT' AS ticker, 'greenidge' AS nombre),
    STRUCT('RGP' AS ticker, 'resources connection' AS nombre),
    STRUCT('CNXN' AS ticker, 'pc connection' AS nombre),
    STRUCT('LUNR' AS ticker, 'intuitive machines' AS nombre),
    STRUCT('SOFI' AS ticker, 'sofi' AS nombre),
    STRUCT('SOFI' AS ticker, 'sofi' AS nombre),
    STRUCT('FGF' AS ticker, 'fundamental global' AS nombre),
    STRUCT('CSX' AS ticker, 'csx' AS nombre),
    STRUCT('PLUG' AS ticker, 'plug power' AS nombre),
    STRUCT('GTES' AS ticker, 'gates industrial' AS nombre),
    STRUCT('SPSC' AS ticker, 's p s commerce' AS nombre),
    STRUCT('SPSC' AS ticker, 'sps commerce' AS nombre),
    STRUCT('HTBK' AS ticker, 'heritage commerce' AS nombre),
    STRUCT('CBSH' AS ticker, 'commerce bancshares' AS nombre),
    STRUCT('WORK' AS ticker, 'slack technologies' AS nombre),
    STRUCT('SNDK' AS ticker, 'sandisk' AS nombre),
    STRUCT('OCGN' AS ticker, 'ocugen' AS nombre),
    STRUCT('GNUS' AS ticker, 'genius brands international' AS nombre),
    STRUCT('STRA' AS ticker, 'strategic education' AS nombre),
    STRUCT('MARA' AS ticker, 'mara' AS nombre),
    STRUCT('MARA' AS ticker, 'mara' AS nombre),
    STRUCT('IDEX' AS ticker, 'ideanomics' AS nombre),
    STRUCT('CCMP' AS ticker, 'cabot microelectronics' AS nombre),
    STRUCT('CCMP' AS ticker, 'cmc materials' AS nombre),
    STRUCT('AAL' AS ticker, 'american airlines' AS nombre),
    STRUCT('APTM' AS ticker, 'alpha partners tech merger' AS nombre),
    STRUCT('BOCH' AS ticker, 'bank of commerce' AS nombre),
    STRUCT('IMCC' AS ticker, 'im cannabis' AS nombre),
    STRUCT('ZEN' AS ticker, 'zendesk' AS nombre),
    STRUCT('DOW' AS ticker, 'dow inc' AS nombre),
    STRUCT('DOW' AS ticker, 'dow chemical' AS nombre),
    STRUCT('RBLX' AS ticker, 'roblox' AS nombre),
    STRUCT('FDX' AS ticker, 'fedex' AS nombre),
    STRUCT('ATVI' AS ticker, 'activision blizzard' AS nombre),
    STRUCT('SSB' AS ticker, 'southstate' AS nombre),
    STRUCT('SPOT' AS ticker, 'spotify technology sa' AS nombre),
    STRUCT('SPOT' AS ticker, 'spotify' AS nombre),
    STRUCT('CS' AS ticker, 'credit suisse' AS nombre),
    STRUCT('SKYX' AS ticker, 's k y x platforms' AS nombre),
    STRUCT('SKYX' AS ticker, 'skyx platforms' AS nombre),
    STRUCT('BBY' AS ticker, 'best buy' AS nombre),
    STRUCT('SENS' AS ticker, 'senseonics' AS nombre),
    STRUCT('SHOP' AS ticker, 'shopify' AS nombre),
    STRUCT('PHM' AS ticker, 'pulte' AS nombre),
    STRUCT('FSLY' AS ticker, 'fastly' AS nombre),
    STRUCT('CSCO' AS ticker, 'cisco systems' AS nombre),
    STRUCT('ZOM' AS ticker, 'zomedica' AS nombre),
    STRUCT('APRN' AS ticker, 'blue apron' AS nombre),
    STRUCT('WTI' AS ticker, 'w&t offshore' AS nombre),
    STRUCT('WTI' AS ticker, 'w & t offshore' AS nombre),
    STRUCT('ZIM' AS ticker, 'zim integrated shipping' AS nombre),
    STRUCT('ZIM' AS ticker, 'zim' AS nombre),
    STRUCT('YELL' AS ticker, 'yellow corp' AS nombre),
    STRUCT('YELL' AS ticker, 'yellow corporation' AS nombre),
    STRUCT('YELL' AS ticker, 'yrc worldwide' AS nombre),
    STRUCT('ACHR' AS ticker, 'archer aviation' AS nombre),
    STRUCT('XOM' AS ticker, 'exxon mobil' AS nombre),
    STRUCT('XOM' AS ticker, 'exxon' AS nombre),
    STRUCT('RIVN' AS ticker, 'rivian' AS nombre),
    STRUCT('IRNT' AS ticker, 'ironnet' AS nombre),
    STRUCT('XSPA' AS ticker, 'xpresspa' AS nombre),
    STRUCT('INO' AS ticker, 'inovio pharmaceuticals' AS nombre),
    STRUCT('FUBO' AS ticker, 'fubotv' AS nombre),
    STRUCT('MVST' AS ticker, 'microvast' AS nombre),
    STRUCT('RIOT' AS ticker, 'riot platforms' AS nombre),
    STRUCT('IEX' AS ticker, 'idex' AS nombre),
    STRUCT('IEX' AS ticker, 'idex corporation' AS nombre),
    STRUCT('MULN' AS ticker, 'mullen automotive' AS nombre),
    STRUCT('AMTD' AS ticker, 'amtd idea' AS nombre),
    STRUCT('AMTD' AS ticker, 'amtd' AS nombre),
    STRUCT('SOUN' AS ticker, 'soundhound ai' AS nombre),
    STRUCT('ICE' AS ticker, 'intercontinentalexchange' AS nombre),
    STRUCT('NBIS' AS ticker, 'nebius' AS nombre),
    STRUCT('QUBT' AS ticker, 'quantum computing' AS nombre),
    STRUCT('ACB' AS ticker, 'aurora cannabis' AS nombre),
    STRUCT('BBAI' AS ticker, 'bigbear ai' AS nombre),
    STRUCT('Z' AS ticker, 'zillow' AS nombre),
    STRUCT('HIMS' AS ticker, 'hims & hers health' AS nombre),
    STRUCT('HIMS' AS ticker, 'hims' AS nombre),
    STRUCT('FSDC' AS ticker, 'fs development' AS nombre),
    STRUCT('MU' AS ticker, 'micron' AS nombre),
    STRUCT('NLIT' AS ticker, 'northern lights acquisition' AS nombre),
    STRUCT('DOCU' AS ticker, 'docusign' AS nombre),
    STRUCT('UPS' AS ticker, 'united parcel service' AS nombre),
    STRUCT('ZG' AS ticker, 'zillow' AS nombre),
    STRUCT('ARC' AS ticker, 'arc document solutions' AS nombre),
    STRUCT('SAVE' AS ticker, 'spirit airlines' AS nombre),
    STRUCT('AZN' AS ticker, 'astrazeneca' AS nombre),
    STRUCT('APLD' AS ticker, 'applied digital' AS nombre),
    STRUCT('KDLY' AS ticker, 'kindly md' AS nombre),
    STRUCT('NILE' AS ticker, 'bitnile' AS nombre),
    STRUCT('PINS' AS ticker, 'pinterest' AS nombre),
    STRUCT('ETH' AS ticker, 'grayscale ethereum' AS nombre),
    STRUCT('RTX' AS ticker, 'rtx' AS nombre),
    STRUCT('RTX' AS ticker, 'raytheon' AS nombre),
    STRUCT('GILD' AS ticker, 'gilead sciences' AS nombre),
    STRUCT('ASO' AS ticker, 'academy sports & outdoors' AS nombre),
    STRUCT('IBKR' AS ticker, 'interactive brokers' AS nombre),
    STRUCT('EXPR' AS ticker, 'express' AS nombre),
    STRUCT('SOS' AS ticker, 'sos limited' AS nombre),
    STRUCT('PSTH' AS ticker, 'pershing sq tontine' AS nombre),
    STRUCT('WFC' AS ticker, 'wells fargo &' AS nombre),
    STRUCT('KEY' AS ticker, 'keycorp' AS nombre),
    STRUCT('DISCA' AS ticker, 'discovery' AS nombre),
    STRUCT('ADBE' AS ticker, 'adobe' AS nombre),
    STRUCT('UUUU' AS ticker, 'energy fuels' AS nombre),
    STRUCT('GHIV' AS ticker, 'gores iv' AS nombre),
    STRUCT('TMC' AS ticker, 'tmc metals' AS nombre),
    STRUCT('PSFE' AS ticker, 'paysafe' AS nombre),
    STRUCT('BAC' AS ticker, 'bank of america' AS nombre),
    STRUCT('PRPL' AS ticker, 'purple innovation' AS nombre),
    STRUCT('NGS' AS ticker, 'natural gas services' AS nombre),
    STRUCT('STAY' AS ticker, 'extended stay america' AS nombre),
    STRUCT('TELL' AS ticker, 'tellurian' AS nombre),
    STRUCT('CRWV' AS ticker, 'coreweave, inc.' AS nombre),
    STRUCT('ATOS' AS ticker, 'atossa therapeutics' AS nombre),
    STRUCT('ON' AS ticker, 'on semiconductor' AS nombre),
    STRUCT('SHLL' AS ticker, 'tortoise acquisition' AS nombre),
    STRUCT('OPEN' AS ticker, 'opendoor technologies' AS nombre),
    STRUCT('JXN' AS ticker, 'jackson financial' AS nombre),
    STRUCT('MTX' AS ticker, 'minerals technologies' AS nombre),
    STRUCT('MARK' AS ticker, 'remark' AS nombre),
    STRUCT('LULU' AS ticker, 'lululemon athletica' AS nombre),
    STRUCT('LULU' AS ticker, 'lulu' AS nombre),
    STRUCT('HKD' AS ticker, 'amtd digital' AS nombre),
    STRUCT('DGLY' AS ticker, 'digital ally' AS nombre),
    STRUCT('COST' AS ticker, 'costco wholesale' AS nombre),
    STRUCT('BFT' AS ticker, 'foley trasimene acq ii' AS nombre),
    STRUCT('DAL' AS ticker, 'delta air lines' AS nombre),
    STRUCT('POET' AS ticker, 'poet technologies' AS nombre),
    STRUCT('ACIU' AS ticker, 'immune' AS nombre),
    STRUCT('OKLO' AS ticker, 'oklo' AS nombre),
    STRUCT('UPST' AS ticker, 'upstart' AS nombre),
    STRUCT('ARM' AS ticker, 'arm holdings' AS nombre),
    STRUCT('TIGR' AS ticker, 'up fintech' AS nombre),
    STRUCT('TIGR' AS ticker, 'tiger brokers' AS nombre),
    STRUCT('BRLI' AS ticker, 'brilliant acquisition' AS nombre),
    STRUCT('VALE' AS ticker, 'vale sa' AS nombre),
    STRUCT('IXHL' AS ticker, 'incannex healthcare' AS nombre),
    STRUCT('MCD' AS ticker, 'mcdonalds' AS nombre),
    STRUCT('AVCT' AS ticker, 'american virtual cloud tech' AS nombre),
    STRUCT('FSR' AS ticker, 'fisker' AS nombre),
    STRUCT('THCB' AS ticker, 'tuscan' AS nombre),
    STRUCT('SOLO' AS ticker, 'electrameccanica vehicles' AS nombre),
    STRUCT('MRVL' AS ticker, 'marvell technology' AS nombre),
    STRUCT('ROAD' AS ticker, 'construction partners' AS nombre),
    STRUCT('LCID' AS ticker, 'lucid motors' AS nombre),
    STRUCT('NEGG' AS ticker, 'newegg commerce' AS nombre),
    STRUCT('BURU' AS ticker, 'nuburu' AS nombre),
    STRUCT('FFIE' AS ticker, 'faraday future intel elctrc' AS nombre),
    STRUCT('UBS' AS ticker, 'ubs' AS nombre),
    STRUCT('NVAX' AS ticker, 'novavax' AS nombre),
    STRUCT('BNGO' AS ticker, 'bionano genomics' AS nombre),
    STRUCT('STET' AS ticker, 'st energy transition i' AS nombre),
    STRUCT('KULR' AS ticker, 'k u l r technology' AS nombre),
    STRUCT('KULR' AS ticker, 'kulr technology' AS nombre),
    STRUCT('HCAC' AS ticker, 'hall chadwick acquisition corp.' AS nombre),
    STRUCT('KTOV' AS ticker, 'kitov pharma' AS nombre),
    STRUCT('LIVE' AS ticker, 'live ventures' AS nombre),
    STRUCT('PENN' AS ticker, 'penn entertainment' AS nombre),
    STRUCT('CHGG' AS ticker, 'chegg' AS nombre),
    STRUCT('SST' AS ticker, 'system1' AS nombre),
    STRUCT('FXLV' AS ticker, 'f45 training' AS nombre),
    STRUCT('IVR' AS ticker, 'invesco mortgage capital' AS nombre),
    STRUCT('XELA' AS ticker, 'exela technologies' AS nombre),
    STRUCT('GSAT' AS ticker, 'globalstar' AS nombre),
    STRUCT('TRKA' AS ticker, 'troika media' AS nombre),
    STRUCT('TGT' AS ticker, 'target' AS nombre),
    STRUCT('GCP' AS ticker, 'gcp applied technologies' AS nombre),
    STRUCT('LUV' AS ticker, 'southwest airlines' AS nombre),
    STRUCT('GOLD' AS ticker, 'barrick gold' AS nombre),
    STRUCT('NAT' AS ticker, 'nordic american tankers' AS nombre),
    STRUCT('REGI' AS ticker, 'renewable energy' AS nombre),
    STRUCT('VIAC' AS ticker, 'viacomcbs' AS nombre),
    STRUCT('CEI' AS ticker, 'camber energy' AS nombre),
    STRUCT('FUSE' AS ticker, 'fusemachines inc.' AS nombre),
    STRUCT('DFLI' AS ticker, 'dragonfly energy' AS nombre),
    STRUCT('GDC' AS ticker, 'gd culture' AS nombre),
    STRUCT('CRSP' AS ticker, 'crispr therapeutics' AS nombre),
    STRUCT('FCEL' AS ticker, 'fuelcell energy' AS nombre),
    STRUCT('CGC' AS ticker, 'canopy growth' AS nombre),
    STRUCT('ENPH' AS ticker, 'enphase energy' AS nombre),
    STRUCT('DASH' AS ticker, 'doordash' AS nombre),
    STRUCT('RGTI' AS ticker, 'rigetti computing' AS nombre),
    STRUCT('VERY' AS ticker, 'vericity' AS nombre),
    STRUCT('SLI' AS ticker, 'standard lithium' AS nombre),
    STRUCT('NUE' AS ticker, 'nucor' AS nombre),
    STRUCT('SRNE' AS ticker, 'sorrento therapeutics' AS nombre),
    STRUCT('BYD' AS ticker, 'boyd gaming' AS nombre),
    STRUCT('IOBT' AS ticker, 'io biotech' AS nombre),
    STRUCT('VLY' AS ticker, 'valley national bancorp' AS nombre),
    STRUCT('NCLH' AS ticker, 'norwegian cruise line' AS nombre),
    STRUCT('CTM' AS ticker, 'castellum' AS nombre),
    STRUCT('QCOM' AS ticker, 'qualcomm' AS nombre),
    STRUCT('WOOF' AS ticker, 'petco health & wellness' AS nombre),
    STRUCT('WOOF' AS ticker, 'petco' AS nombre),
    STRUCT('IZEA' AS ticker, 'izea' AS nombre),
    STRUCT('IPOF' AS ticker, 'social cap hedo vi' AS nombre),
    STRUCT('AUVI' AS ticker, 'applied uv' AS nombre),
    STRUCT('BULL' AS ticker, 'webull' AS nombre),
    STRUCT('ATCH' AS ticker, 'atlasclear' AS nombre),
    STRUCT('DISCB' AS ticker, 'discovery' AS nombre),
    STRUCT('CMC' AS ticker, 'commercial metals' AS nombre),
    STRUCT('FTIV' AS ticker, 'fintech acquisition iv' AS nombre),
    STRUCT('CASH' AS ticker, 'pathward financial' AS nombre),
    STRUCT('RVSN' AS ticker, 'rail vision' AS nombre),
    STRUCT('VXRT' AS ticker, 'vaxart' AS nombre),
    STRUCT('IREN' AS ticker, 'iren' AS nombre),
    STRUCT('SAVA' AS ticker, 'cassava sciences' AS nombre),
    STRUCT('LHX' AS ticker, 'l3harris technologies' AS nombre),
    STRUCT('LHX' AS ticker, 'harris' AS nombre),
    STRUCT('PANW' AS ticker, 'palo alto networks' AS nombre),
    STRUCT('OPTT' AS ticker, 'ocean power technologies' AS nombre),
    STRUCT('CRCL' AS ticker, 'circle internet group, inc. class common stock' AS nombre),
    STRUCT('MASS' AS ticker, '908 devices' AS nombre),
    STRUCT('XPEV' AS ticker, 'xpeng' AS nombre),
    STRUCT('LAZR' AS ticker, 'luminar technologies' AS nombre),
    STRUCT('SEGG' AS ticker, 'sports entertainment gaming global' AS nombre),
    STRUCT('VTIQ' AS ticker, 'vectoiq acquisition ii' AS nombre),
    STRUCT('PPSI' AS ticker, 'pioneer power solutions' AS nombre),
    STRUCT('CUK' AS ticker, 'carnival' AS nombre),
    STRUCT('DISCK' AS ticker, 'discovery' AS nombre),
    STRUCT('TETC' AS ticker, 'tech & energy transition' AS nombre),
    STRUCT('CAR' AS ticker, 'avis budget' AS nombre),
    STRUCT('SBE' AS ticker, 'switchback energy' AS nombre),
    STRUCT('SBE' AS ticker, 'chargepoint' AS nombre),
    STRUCT('GIK' AS ticker, 'gigcapital3' AS nombre),
    STRUCT('NXPI' AS ticker, 'nxp semiconductors' AS nombre),
    STRUCT('NXPI' AS ticker, 'nxp' AS nombre),
    STRUCT('RCL' AS ticker, 'royal caribbean cruises' AS nombre),
    STRUCT('LLY' AS ticker, 'eli lilly & company' AS nombre),
    STRUCT('DELL' AS ticker, 'dell technologies' AS nombre),
    STRUCT('SKLZ' AS ticker, 'skillz' AS nombre),
    STRUCT('CELH' AS ticker, 'celsius' AS nombre),
    STRUCT('CAP' AS ticker, 'capitol investment' AS nombre),
    STRUCT('CAP' AS ticker, 'doma' AS nombre),
    STRUCT('LGVN' AS ticker, 'longeveron' AS nombre),
    STRUCT('ATGL' AS ticker, 'alpha technology' AS nombre),
    STRUCT('CTXR' AS ticker, 'citius pharmaceuticals' AS nombre),
    STRUCT('ROKU' AS ticker, 'roku' AS nombre),
    STRUCT('AMCX' AS ticker, 'amc networks' AS nombre),
    STRUCT('CVS' AS ticker, 'cvs health' AS nombre),
    STRUCT('CVS' AS ticker, 'cvs' AS nombre),
    STRUCT('CTRM' AS ticker, 'castor maritime' AS nombre),
    STRUCT('BIOT' AS ticker, 'biotech acquisition' AS nombre),
    STRUCT('UAL' AS ticker, 'united airlines' AS nombre),
    STRUCT('PHX' AS ticker, 'p h x minerals' AS nombre),
    STRUCT('PHX' AS ticker, 'phx minerals' AS nombre),
    STRUCT('PRTY' AS ticker, 'party city holdco' AS nombre),
    STRUCT('EAT' AS ticker, 'brinker international' AS nombre),
    STRUCT('CAT' AS ticker, 'caterpillar' AS nombre),
    STRUCT('PHUN' AS ticker, 'phunware' AS nombre),
    STRUCT('FMCI' AS ticker, 'forum merger ii' AS nombre),
    STRUCT('ESTA' AS ticker, 'establishment labs' AS nombre),
    STRUCT('ONDS' AS ticker, 'ondas' AS nombre),
    STRUCT('DBX' AS ticker, 'dropbox' AS nombre),
    STRUCT('FTCV' AS ticker, 'fintech acquisition corp v' AS nombre),
    STRUCT('FTCV' AS ticker, 'etoro' AS nombre),
    STRUCT('MMAT' AS ticker, 'meta materials' AS nombre),
    STRUCT('KSS' AS ticker, 'kohls' AS nombre),
    STRUCT('HPE' AS ticker, 'hewlett packard enterprise' AS nombre),
    STRUCT('TDOC' AS ticker, 'teladoc health' AS nombre),
    STRUCT('TRCH' AS ticker, 'torchlight energy resources' AS nombre),
    STRUCT('VS' AS ticker, 'versus systems' AS nombre),
    STRUCT('UBER' AS ticker, 'uber' AS nombre),
    STRUCT('HYLN' AS ticker, 'hyliion' AS nombre),
    STRUCT('OXY' AS ticker, 'occidental petroleum' AS nombre),
    STRUCT('BOOM' AS ticker, 'dmc global' AS nombre),
    STRUCT('RBC' AS ticker, 'rbc bearings' AS nombre),
    STRUCT('WAT' AS ticker, 'waters' AS nombre),
    STRUCT('DAWN' AS ticker, 'day one biopharmaceuticals' AS nombre),
    STRUCT('LVS' AS ticker, 'las vegas sands' AS nombre),
    STRUCT('BERY' AS ticker, 'berry global' AS nombre),
    STRUCT('HD' AS ticker, 'home depot' AS nombre),
    STRUCT('RDBX' AS ticker, 'redbox entertainment' AS nombre),
    STRUCT('ASST' AS ticker, 'asset entities' AS nombre),
    STRUCT('SLS' AS ticker, 'sellas life sciences' AS nombre),
    STRUCT('BRY' AS ticker, 'berry' AS nombre),
    STRUCT('LCA' AS ticker, 'landcadia iv' AS nombre),
    STRUCT('HEAR' AS ticker, 'turtle beach' AS nombre),
    STRUCT('ELF' AS ticker, 'e l f beauty' AS nombre),
    STRUCT('ELF' AS ticker, 'elf beauty' AS nombre),
    STRUCT('WOLF' AS ticker, 'wolfspeed' AS nombre),
    STRUCT('LMT' AS ticker, 'lockheed martin' AS nombre),
    STRUCT('W' AS ticker, 'wayfair' AS nombre),
    STRUCT('NGA' AS ticker, 'northern genesis acquisition' AS nombre),
    STRUCT('NGA' AS ticker, 'lion electric' AS nombre),
    STRUCT('LAC' AS ticker, 'lithium americas' AS nombre),
    STRUCT('NYC' AS ticker, 'american strategic investment' AS nombre),
    STRUCT('OTAI' AS ticker, 'starlink ai acquisition ordinary shares' AS nombre),
    STRUCT('NAK' AS ticker, 'northern dynasty minerals' AS nombre),
    STRUCT('CIIC' AS ticker, 'ciig merger' AS nombre),
    STRUCT('WNEB' AS ticker, 'western england bancorp' AS nombre),
    STRUCT('SKY' AS ticker, 'champion homes' AS nombre),
    STRUCT('WASH' AS ticker, 'washington bancorp' AS nombre),
    STRUCT('NNDM' AS ticker, 'nano dimension' AS nombre),
    STRUCT('GS' AS ticker, 'goldman sachs' AS nombre),
    STRUCT('ABNB' AS ticker, 'airbnb' AS nombre),
    STRUCT('MAC' AS ticker, 'macerich' AS nombre),
    STRUCT('NPA' AS ticker, 'new providence acquisition' AS nombre),
    STRUCT('NPA' AS ticker, 'ast spacemobile' AS nombre),
    STRUCT('HES' AS ticker, 'hess' AS nombre),
    STRUCT('VLDR' AS ticker, 'velodyne lidar' AS nombre),
    STRUCT('AGC' AS ticker, 'altimeter growth' AS nombre),
    STRUCT('IBRX' AS ticker, 'immunitybio' AS nombre),
    STRUCT('UAVS' AS ticker, 'ageagle aerial systems' AS nombre),
    STRUCT('OPAD' AS ticker, 'offerpad solutions' AS nombre),
    STRUCT('BGFV' AS ticker, 'big 5 sporting goods' AS nombre),
    STRUCT('BGS' AS ticker, 'b&g foods' AS nombre),
    STRUCT('BGS' AS ticker, 'b & g foods' AS nombre),
    STRUCT('GXO' AS ticker, 'g x o logistics' AS nombre),
    STRUCT('GXO' AS ticker, 'gxo logistics' AS nombre),
    STRUCT('INSE' AS ticker, 'inspired entertainment' AS nombre),
    STRUCT('ICBK' AS ticker, 'county bancorp' AS nombre),
    STRUCT('SHIP' AS ticker, 'seanergy maritime' AS nombre),
    STRUCT('AMAT' AS ticker, 'applied materials' AS nombre),
    STRUCT('VET' AS ticker, 'vermilion energy' AS nombre),
    STRUCT('FTOC' AS ticker, 'ftac olympus acquisition' AS nombre),
    STRUCT('AFRM' AS ticker, 'affirm' AS nombre),
    STRUCT('KODK' AS ticker, 'eastman kodak' AS nombre),
    STRUCT('NUAI' AS ticker, 'era energy & digital, inc.' AS nombre),
    STRUCT('PTRA' AS ticker, 'proterra' AS nombre),
    STRUCT('NVO' AS ticker, 'novo nordisk a/s' AS nombre),
    STRUCT('LODE' AS ticker, 'comstock' AS nombre),
    STRUCT('JMIA' AS ticker, 'jumia technologies' AS nombre),
    STRUCT('JMIA' AS ticker, 'jumia' AS nombre),
    STRUCT('REV' AS ticker, 'revlon' AS nombre),
    STRUCT('FLY' AS ticker, 'firefly aerospace inc.' AS nombre),
    STRUCT('ESSC' AS ticker, 'east stone acquisition' AS nombre),
    STRUCT('NOEM' AS ticker, 'co2 energy transition corp.' AS nombre),
    STRUCT('EURN' AS ticker, 'euronav' AS nombre),
    STRUCT('IBM' AS ticker, 'international business machs cor' AS nombre),
    STRUCT('KOSS' AS ticker, 'koss' AS nombre),
    STRUCT('BYFC' AS ticker, 'broadway financial' AS nombre),
    STRUCT('HOPE' AS ticker, 'hope bancorp' AS nombre),
    STRUCT('PACW' AS ticker, 'pacwest bancorp de' AS nombre),
    STRUCT('LDI' AS ticker, 'loandepot' AS nombre),
    STRUCT('CSOD' AS ticker, 'cornerstone ondemand' AS nombre),
    STRUCT('MSGN' AS ticker, 'm s g networks' AS nombre),
    STRUCT('MSGN' AS ticker, 'msg networks' AS nombre),
    STRUCT('CCX' AS ticker, 'churchill capital ii' AS nombre),
    STRUCT('AIRE' AS ticker, 'realpha tech' AS nombre),
    STRUCT('ATEN' AS ticker, 'a10 networks' AS nombre),
    STRUCT('THC' AS ticker, 'tenet healthcare' AS nombre),
    STRUCT('FOSL' AS ticker, 'fossil' AS nombre),
    STRUCT('TXG' AS ticker, '10x genomics' AS nombre),
    STRUCT('TTOO' AS ticker, 't2 biosystems' AS nombre),
    STRUCT('DDOG' AS ticker, 'datadog' AS nombre),
    STRUCT('F' AS ticker, 'ford motor' AS nombre),
    STRUCT('LMND' AS ticker, 'lemonade' AS nombre),
    STRUCT('KR' AS ticker, 'kroger' AS nombre),
    STRUCT('AMP' AS ticker, 'ameriprise financial' AS nombre),
    STRUCT('SIRI' AS ticker, 'sirius xm' AS nombre),
    STRUCT('SIRI' AS ticker, 'siriusxm' AS nombre),
    STRUCT('GBNY' AS ticker, 'generations bancorp' AS nombre),
    STRUCT('WWE' AS ticker, 'world wrestling' AS nombre),
    STRUCT('APXT' AS ticker, 'apex treasury' AS nombre),
    STRUCT('ANTM' AS ticker, 'anthem' AS nombre),
    STRUCT('GRUB' AS ticker, 'grubhub' AS nombre),
    STRUCT('GRUB' AS ticker, 'just eat takeaway' AS nombre),
    STRUCT('MORN' AS ticker, 'morningstar' AS nombre),
    STRUCT('REE' AS ticker, 'r e e automotive' AS nombre),
    STRUCT('REE' AS ticker, 'ree automotive' AS nombre),
    STRUCT('NVOS' AS ticker, 'novo integrated sciences' AS nombre),
    STRUCT('CHPT' AS ticker, 'chargepoint' AS nombre),
    STRUCT('CHK' AS ticker, 'chesapeake energy' AS nombre),
    STRUCT('PATH' AS ticker, 'uipath' AS nombre),
    STRUCT('CYN' AS ticker, 'cyngn' AS nombre),
    STRUCT('NVNI' AS ticker, 'nvni group limited' AS nombre),
    STRUCT('ASRT' AS ticker, 'assertio' AS nombre),
    STRUCT('DFS' AS ticker, 'discover financial services' AS nombre),
    STRUCT('AG' AS ticker, 'first majestic silver' AS nombre),
    STRUCT('USFD' AS ticker, 'us foods' AS nombre),
    STRUCT('MKSI' AS ticker, 'm k s instruments' AS nombre),
    STRUCT('MKSI' AS ticker, 'mks instruments' AS nombre),
    STRUCT('GCT' AS ticker, 'gigacloud technology' AS nombre),
    STRUCT('MT' AS ticker, 'arcelormittal sa luxembourg' AS nombre),
    STRUCT('MT' AS ticker, 'arcelormittal sa' AS nombre),
    STRUCT('OPK' AS ticker, 'opko health' AS nombre),
    STRUCT('BKNG' AS ticker, 'booking' AS nombre),
    STRUCT('ELS' AS ticker, 'equity lifestyle properties' AS nombre),
    STRUCT('CCXI' AS ticker, 'churchill capital xi' AS nombre),
    STRUCT('WOW' AS ticker, 'wideopenwest' AS nombre),
    STRUCT('LUMN' AS ticker, 'lumen techologies' AS nombre),
    STRUCT('BRO' AS ticker, 'brown & brown' AS nombre),
    STRUCT('SCWO' AS ticker, '374water' AS nombre),
    STRUCT('ACQR' AS ticker, 'independence holdings' AS nombre),
    STRUCT('FRX' AS ticker, 'forest road acquisition' AS nombre),
    STRUCT('DVLT' AS ticker, 'datavault ai (antes wisa technologies)' AS nombre),
    STRUCT('STNG' AS ticker, 'scorpio tankers' AS nombre),
    STRUCT('PRTH' AS ticker, 'priority technology' AS nombre),
    STRUCT('EBAY' AS ticker, 'ebay' AS nombre),
    STRUCT('HUYA' AS ticker, 'huya' AS nombre),
    STRUCT('PSTV' AS ticker, 'plus therapeutics' AS nombre),
    STRUCT('VEL' AS ticker, 'velocity financial' AS nombre),
    STRUCT('NBRV' AS ticker, 'nabriva therapeutics' AS nombre),
    STRUCT('CVX' AS ticker, 'chevron' AS nombre),
    STRUCT('SNR' AS ticker, 'senior investment' AS nombre),
    STRUCT('DPZ' AS ticker, 'domino\'s pizza inc' AS nombre),
    STRUCT('MRO' AS ticker, 'marathon oil' AS nombre),
    STRUCT('RPAY' AS ticker, 'repay' AS nombre),
    STRUCT('FAST' AS ticker, 'fastenal' AS nombre),
    STRUCT('WAL' AS ticker, 'western alliance bancorporation' AS nombre),
    STRUCT('CRTX' AS ticker, 'cortexyme' AS nombre),
    STRUCT('IPOD' AS ticker, 'social cap hedo iv' AS nombre),
    STRUCT('PATK' AS ticker, 'patrick industries' AS nombre),
    STRUCT('IONQ' AS ticker, 'ionq' AS nombre),
    STRUCT('RAPT' AS ticker, 'rapt therapeutics' AS nombre),
    STRUCT('HCTI' AS ticker, 'healthcare triangle' AS nombre),
    STRUCT('GRAF' AS ticker, 'graf global' AS nombre),
    STRUCT('ZNGA' AS ticker, 'zynga' AS nombre),
    STRUCT('APT' AS ticker, 'alpha pro tech' AS nombre),
    STRUCT('QBTS' AS ticker, 'd-wave quantum' AS nombre),
    STRUCT('QBTS' AS ticker, 'd-wave' AS nombre),
    STRUCT('BKKT' AS ticker, 'bakkt' AS nombre),
    STRUCT('LNG' AS ticker, 'cheniere energy' AS nombre),
    STRUCT('MRIN' AS ticker, 'marin software' AS nombre),
    STRUCT('WBD' AS ticker, 'warner bros discovery' AS nombre),
    STRUCT('EONR' AS ticker, 'eon resources' AS nombre),
    STRUCT('EYES' AS ticker, 'second sight medical products in' AS nombre),
    STRUCT('CVLB' AS ticker, 'conversion labs' AS nombre),
    STRUCT('SPPI' AS ticker, 'spectrum pharmaceuticals' AS nombre),
    STRUCT('DOOR' AS ticker, 'masonite international' AS nombre),
    STRUCT('NYT' AS ticker, 'the new york times company' AS nombre),
    STRUCT('VACQ' AS ticker, 'vector acquisition' AS nombre),
    STRUCT('ISPC' AS ticker, 'ispecimen' AS nombre),
    STRUCT('DHT' AS ticker, 'dht holdings' AS nombre),
    STRUCT('CZR' AS ticker, 'caesars entertainment de' AS nombre),
    STRUCT('BLNK' AS ticker, 'blink charging' AS nombre),
    STRUCT('RTP' AS ticker, 'reinvent technology partners' AS nombre),
    STRUCT('BNTX' AS ticker, 'biontech se' AS nombre),
    STRUCT('GEVO' AS ticker, 'gevo, inc' AS nombre),
    STRUCT('FCN' AS ticker, 'f t i consulting' AS nombre),
    STRUCT('FCN' AS ticker, 'fti consulting' AS nombre),
    STRUCT('ALLY' AS ticker, 'ally financial' AS nombre),
    STRUCT('OPES' AS ticker, 'opes acquisition' AS nombre),
    STRUCT('UONE' AS ticker, 'urban one' AS nombre),
    STRUCT('SLGG' AS ticker, 'super league gaming' AS nombre),
    STRUCT('IPOC' AS ticker, 'social cap hedo iii' AS nombre),
    STRUCT('COTY' AS ticker, 'coty, inc' AS nombre),
    STRUCT('RCAT' AS ticker, 'red cat' AS nombre),
    STRUCT('GTHX' AS ticker, 'g1 therapeutics' AS nombre),
    STRUCT('TUP' AS ticker, 'tupperware brands' AS nombre),
    STRUCT('LPL' AS ticker, 'lg display' AS nombre),
    STRUCT('RJAC' AS ticker, 'jackson acquisition' AS nombre),
    STRUCT('MS' AS ticker, 'morgan stanley dean witter &' AS nombre),
    STRUCT('JACS' AS ticker, 'jackson acquisition ii class ordinary shares' AS nombre),
    STRUCT('DIDI' AS ticker, 'didi global' AS nombre),
    STRUCT('SNPR' AS ticker, 'tortoise acquisition ii' AS nombre),
    STRUCT('OCC' AS ticker, 'optical cable' AS nombre),
    STRUCT('HRC' AS ticker, 'hill rom' AS nombre),
    STRUCT('COSM' AS ticker, 'cosmos health' AS nombre),
    STRUCT('HFFG' AS ticker, 'h f foods' AS nombre),
    STRUCT('HFFG' AS ticker, 'hf foods' AS nombre),
    STRUCT('HOLO' AS ticker, 'microcloud hologram' AS nombre),
    STRUCT('GFL' AS ticker, 'g f l environmental' AS nombre),
    STRUCT('GFL' AS ticker, 'gfl environmental' AS nombre),
    STRUCT('TTWO' AS ticker, 'take-two interactive software, inc' AS nombre),
    STRUCT('TTWO' AS ticker, 'take two interactive software, inc' AS nombre),
    STRUCT('SPB' AS ticker, 'spectrum brands' AS nombre),
    STRUCT('CECE' AS ticker, 'ceco environmental' AS nombre),
    STRUCT('BFRI' AS ticker, 'biofrontera' AS nombre),
    STRUCT('PLAN' AS ticker, 'anaplan' AS nombre),
    STRUCT('NATI' AS ticker, 'national instruments' AS nombre),
    STRUCT('GPRO' AS ticker, 'gopro' AS nombre),
    STRUCT('CCJ' AS ticker, 'cameco corporation' AS nombre),
    STRUCT('VIH' AS ticker, 'vpc impact acquisition' AS nombre),
    STRUCT('VIH' AS ticker, 'bakkt' AS nombre),
    STRUCT('ASML' AS ticker, 'asml' AS nombre),
    STRUCT('MFA' AS ticker, 'mfa financial' AS nombre),
    STRUCT('CLX' AS ticker, 'clorox' AS nombre),
    STRUCT('BUD' AS ticker, 'anheuser busch inbev' AS nombre),
    STRUCT('ULTA' AS ticker, 'ulta beauty' AS nombre),
    STRUCT('DNN' AS ticker, 'denison mines' AS nombre),
    STRUCT('VTVT' AS ticker, 'v t v therapeutics' AS nombre),
    STRUCT('VTVT' AS ticker, 'vtv therapeutics' AS nombre),
    STRUCT('BWAC' AS ticker, 'better world acquisition' AS nombre),
    STRUCT('SPWR' AS ticker, 'sunpower inc.' AS nombre),
    STRUCT('POW' AS ticker, 'powered brands' AS nombre),
    STRUCT('TGTX' AS ticker, 't g therapeutics' AS nombre),
    STRUCT('TGTX' AS ticker, 'tg therapeutics' AS nombre),
    STRUCT('AYTU' AS ticker, 'aytu biopharma' AS nombre),
    STRUCT('ABAT' AS ticker, 'american battery technology' AS nombre),
    STRUCT('GNS' AS ticker, 'genius' AS nombre),
    STRUCT('GPI' AS ticker, '1 automotive' AS nombre),
    STRUCT('TBLT' AS ticker, 'toughbuilt industries' AS nombre),
    STRUCT('LTC' AS ticker, 'ltc properties' AS nombre),
    STRUCT('GRND' AS ticker, 'grindr' AS nombre),
    STRUCT('CCCC' AS ticker, 'c4 therapeutics' AS nombre),
    STRUCT('TCRR' AS ticker, 'tcr2 therapeutics' AS nombre),
    STRUCT('NKE' AS ticker, 'nike' AS nombre),
    STRUCT('PTCT' AS ticker, 'ptc therapeutics' AS nombre),
    STRUCT('ADCT' AS ticker, 'adc therapeutics sa' AS nombre),
    STRUCT('RACA' AS ticker, 'therapeutics acquisition' AS nombre),
    STRUCT('METX' AS ticker, 'btc digital' AS nombre),
    STRUCT('GNC' AS ticker, 'gnc' AS nombre),
    STRUCT('SIGA' AS ticker, 'siga technologies' AS nombre),
    STRUCT('SIGA' AS ticker, 'siga' AS nombre),
    STRUCT('NCNA' AS ticker, 'nucana' AS nombre),
    STRUCT('MOD' AS ticker, 'modine manufacturing' AS nombre),
    STRUCT('HMHC' AS ticker, 'houghton mifflin harcourt' AS nombre),
    STRUCT('SIX' AS ticker, 'six flags entertainment' AS nombre),
    STRUCT('NRZ' AS ticker, 'residential investment' AS nombre),
    STRUCT('DB' AS ticker, 'deutsche bank ag' AS nombre),
    STRUCT('MAR' AS ticker, 'marriott international' AS nombre),
    STRUCT('RZLV' AS ticker, 'rezolve ai' AS nombre),
    STRUCT('GMBL' AS ticker, 'esports entertainment group inc' AS nombre),
    STRUCT('FNKO' AS ticker, 'funko' AS nombre),
    STRUCT('SNOW' AS ticker, 'snowflake' AS nombre),
    STRUCT('LOGI' AS ticker, 'logitech international' AS nombre),
    STRUCT('BMBL' AS ticker, 'bumble' AS nombre),
    STRUCT('STLD' AS ticker, 'steel dynamics' AS nombre),
    STRUCT('HPQ' AS ticker, 'hp inc' AS nombre),
    STRUCT('NMAX' AS ticker, 'newsmax, inc. class common stock' AS nombre),
    STRUCT('SOBR' AS ticker, 'sobr safe inc' AS nombre),
    STRUCT('ZEAL' AS ticker, 'zealand pharma a/s' AS nombre),
    STRUCT('GCTK' AS ticker, 'glucotrack' AS nombre),
    STRUCT('AIN' AS ticker, 'albany international' AS nombre),
    STRUCT('IPOB' AS ticker, 'social cap hedo ii' AS nombre),
    STRUCT('LYV' AS ticker, 'live nation entertainment' AS nombre),
    STRUCT('CLVS' AS ticker, 'clovis oncology' AS nombre),
    STRUCT('STIC' AS ticker, 'northern star acquisition' AS nombre),
    STRUCT('HLBZ' AS ticker, 'helbiz' AS nombre),
    STRUCT('PIC' AS ticker, 'pivotal investment ii' AS nombre),
    STRUCT('BACK' AS ticker, 'imac holdings' AS nombre),
    STRUCT('DEAC' AS ticker, 'diamond eagle acquisition' AS nombre),
    STRUCT('TXMD' AS ticker, 'therapeuticsmd' AS nombre),
    STRUCT('PEW' AS ticker, 'grabagun digital inc. common stock' AS nombre),
    STRUCT('ELY' AS ticker, 'callaway golf' AS nombre),
    STRUCT('BCRX' AS ticker, 'biocryst pharmaceuticals' AS nombre),
    STRUCT('WEBR' AS ticker, 'weber' AS nombre),
    STRUCT('SGRY' AS ticker, 'surgery partners' AS nombre),
    STRUCT('RMO' AS ticker, 'romeo power' AS nombre),
    STRUCT('PCG' AS ticker, 'pg&e corporation' AS nombre),
    STRUCT('CARE' AS ticker, 'carter bankshares' AS nombre),
    STRUCT('SPAQ' AS ticker, 'listed funds' AS nombre),
    STRUCT('VFF' AS ticker, 'village farms international' AS nombre),
    STRUCT('JOB' AS ticker, 'gee' AS nombre),
    STRUCT('SFTW' AS ticker, 'osprey technology acquisition' AS nombre),
    STRUCT('SFTW' AS ticker, 'blacksky' AS nombre),
    STRUCT('DCRC' AS ticker, 'decarbonization pl acq iii' AS nombre),
    STRUCT('GSAH' AS ticker, 'gs acquisition holdings' AS nombre),
    STRUCT('GSAH' AS ticker, 'mirion technologies' AS nombre),
    STRUCT('CJJD' AS ticker, 'china jo jo drugstores' AS nombre),
    STRUCT('MOBX' AS ticker, 'mobix labs' AS nombre),
    STRUCT('FAMI' AS ticker, 'farmmi' AS nombre),
    STRUCT('LYFT' AS ticker, 'lyft' AS nombre),
    STRUCT('FRO' AS ticker, 'frontline' AS nombre),
    STRUCT('FCCY' AS ticker, '1st constitution bancorp' AS nombre),
    STRUCT('ARVL' AS ticker, 'arrival' AS nombre),
    STRUCT('ALGN' AS ticker, 'align technology' AS nombre),
    STRUCT('BEAT' AS ticker, 'heartbeam' AS nombre),
    STRUCT('SPIR' AS ticker, 'spire global' AS nombre),
    STRUCT('NBA' AS ticker, 'beginnings acquisition' AS nombre),
    STRUCT('DISH' AS ticker, 'dish network' AS nombre),
    STRUCT('DEI' AS ticker, 'douglas emmett' AS nombre),
    STRUCT('WDC' AS ticker, 'western digital' AS nombre),
    STRUCT('IHC' AS ticker, 'independence' AS nombre),
    STRUCT('OSK' AS ticker, 'oshkosh' AS nombre),
    STRUCT('EBON' AS ticker, 'ebang international' AS nombre),
    STRUCT('THCA' AS ticker, 'tuscan ii' AS nombre),
    STRUCT('GAN' AS ticker, 'gan limited' AS nombre),
    STRUCT('RILY' AS ticker, 'riley financial' AS nombre),
    STRUCT('BODY' AS ticker, 'beachbody' AS nombre),
    STRUCT('CBD' AS ticker, 'companhia brasileira de dist' AS nombre),
    STRUCT('DOMO' AS ticker, 'domo' AS nombre),
    STRUCT('SHOT' AS ticker, 'safety shot' AS nombre),
    STRUCT('CAVA' AS ticker, 'cava' AS nombre),
    STRUCT('GWAV' AS ticker, 'greenwave tech solutions' AS nombre),
    STRUCT('AZZ' AS ticker, 'azz' AS nombre),
    STRUCT('BOX' AS ticker, 'box' AS nombre),
    STRUCT('TWLO' AS ticker, 'twilio' AS nombre),
    STRUCT('BIDU' AS ticker, 'baidu' AS nombre),
    STRUCT('OBNK' AS ticker, 'origin bancorp' AS nombre),
    STRUCT('KNDI' AS ticker, 'kandi technologies' AS nombre),
    STRUCT('IEC' AS ticker, 'iec electronics' AS nombre),
    STRUCT('CLBR' AS ticker, 'colombier acquisition ii' AS nombre),
    STRUCT('FOLD' AS ticker, 'amicus therapeutics' AS nombre),
    STRUCT('RDW' AS ticker, 'redwire' AS nombre),
    STRUCT('BTX' AS ticker, 'blackrock technology and private equity term common shares of beneficial interest' AS nombre),
    STRUCT('OEG' AS ticker, 'orbital energy' AS nombre),
    STRUCT('MCFE' AS ticker, 'mcafee' AS nombre),
    STRUCT('BARK' AS ticker, 'bark' AS nombre),
    STRUCT('PTPI' AS ticker, 'petros pharmaceuticals' AS nombre),
    STRUCT('KEN' AS ticker, 'kenon' AS nombre),
    STRUCT('CPA' AS ticker, 'copa' AS nombre),
    STRUCT('WYNN' AS ticker, 'wynn resorts' AS nombre),
    STRUCT('XTIA' AS ticker, 'xti aerospace' AS nombre),
    STRUCT('BFLY' AS ticker, 'butterfly network' AS nombre),
    STRUCT('LGND' AS ticker, 'ligand pharmaceuticals' AS nombre),
    STRUCT('HAL' AS ticker, 'halliburton' AS nombre),
    STRUCT('MTCH' AS ticker, 'match' AS nombre),
    STRUCT('PLUS' AS ticker, 'eplus' AS nombre),
    STRUCT('CCV' AS ticker, 'churchill capital v' AS nombre),
    STRUCT('BIGC' AS ticker, 'bigcommerce' AS nombre),
    STRUCT('NET' AS ticker, 'cloudflare' AS nombre),
    STRUCT('AYRO' AS ticker, 'ayro' AS nombre),
    STRUCT('RAYA' AS ticker, 'erayak power solution' AS nombre),
    STRUCT('VGAC' AS ticker, 'vg acquisition' AS nombre),
    STRUCT('VGAC' AS ticker, '23andme' AS nombre),
    STRUCT('GTIM' AS ticker, 'good times restaurants' AS nombre),
    STRUCT('FPAC' AS ticker, 'far peak acquisition' AS nombre),
    STRUCT('ALCC' AS ticker, 'altc acquisition' AS nombre),
    STRUCT('DLTR' AS ticker, 'dollar tree' AS nombre),
    STRUCT('RAD' AS ticker, 'rite aid' AS nombre),
    STRUCT('YYAI' AS ticker, 'connexa sports technologies' AS nombre),
    STRUCT('FEMY' AS ticker, 'femasys' AS nombre),
    STRUCT('GTE' AS ticker, 'gran tierra energy' AS nombre),
    STRUCT('LVGO' AS ticker, 'livongo health' AS nombre),
    STRUCT('ACH' AS ticker, 'accendra health, inc. common stock' AS nombre),
    STRUCT('OSTK' AS ticker, 'overstock' AS nombre),
    STRUCT('ERIC' AS ticker, 'ericsson' AS nombre),
    STRUCT('LGVW' AS ticker, 'longview acquisition' AS nombre),
    STRUCT('MAXN' AS ticker, 'maxeon solar technologies' AS nombre),
    STRUCT('SWBI' AS ticker, 'smith & wesson brands' AS nombre),
    STRUCT('EVFM' AS ticker, 'evofem biosciences' AS nombre),
    STRUCT('FIII' AS ticker, 'forum merger iii' AS nombre),
    STRUCT('FLIR' AS ticker, 'flir systems' AS nombre),
    STRUCT('USCR' AS ticker, 'us concrete' AS nombre),
    STRUCT('GPUS' AS ticker, 'hyperscale data' AS nombre),
    STRUCT('VISL' AS ticker, 'vislink technologies' AS nombre),
    STRUCT('MRK' AS ticker, 'merck &' AS nombre),
    STRUCT('KCAC' AS ticker, 'kensington capital acq ii' AS nombre),
    STRUCT('AUY' AS ticker, 'yamana gold' AS nombre),
    STRUCT('BBW' AS ticker, 'build bear workshop' AS nombre),
    STRUCT('LFVN' AS ticker, 'lifevantage' AS nombre),
    STRUCT('CRY' AS ticker, 'cryolife' AS nombre),
    STRUCT('ETSY' AS ticker, 'etsy' AS nombre),
    STRUCT('QLGN' AS ticker, 'qualigen therapeutics' AS nombre),
    STRUCT('AGO' AS ticker, 'assured guaranty' AS nombre),
    STRUCT('RMG' AS ticker, 'rmg acquisition' AS nombre),
    STRUCT('RMG' AS ticker, 'romeo power' AS nombre),
    STRUCT('BETS' AS ticker, 'bit brother' AS nombre),
    STRUCT('TRVN' AS ticker, 'trevena' AS nombre),
    STRUCT('LK' AS ticker, 'luckin coffee' AS nombre),
    STRUCT('COKE' AS ticker, 'coca cola consolidated' AS nombre),
    STRUCT('JCP' AS ticker, 'jcpenney' AS nombre),
    STRUCT('JCP' AS ticker, 'jc penney' AS nombre),
    STRUCT('JCP' AS ticker, 'j.c. penney' AS nombre),
    STRUCT('INFO' AS ticker, 'ihs markit' AS nombre),
    STRUCT('CUZ' AS ticker, 'cousins properties' AS nombre),
    STRUCT('AVPT' AS ticker, 'avepoint' AS nombre),
    STRUCT('TTCF' AS ticker, 'tattooed chef' AS nombre),
    STRUCT('FEYE' AS ticker, 'fireeye' AS nombre),
    STRUCT('HOME' AS ticker, 'at home' AS nombre),
    STRUCT('AAXN' AS ticker, 'axon enterprise' AS nombre),
    STRUCT('TNXP' AS ticker, 'tonix pharmaceuticals' AS nombre),
    STRUCT('TWNK' AS ticker, 'hostess brands' AS nombre),
    STRUCT('CNK' AS ticker, 'cinemark' AS nombre),
    STRUCT('ESI' AS ticker, 'element solutions' AS nombre),
    STRUCT('AGTC' AS ticker, 'applied genetic technologies cor' AS nombre),
    STRUCT('MCO' AS ticker, 'moodys' AS nombre),
    STRUCT('CFVI' AS ticker, 'cf acquisition vi' AS nombre),
    STRUCT('CFVI' AS ticker, 'rumble' AS nombre),
    STRUCT('SCHW' AS ticker, 'schwab charles' AS nombre),
    STRUCT('PEAK' AS ticker, 'healthpeak properties' AS nombre),
    STRUCT('TR' AS ticker, 'tootsie roll' AS nombre),
    STRUCT('PCSA' AS ticker, 'processa pharmaceuticals' AS nombre),
    STRUCT('CLII' AS ticker, 'climate change crisis real impact' AS nombre),
    STRUCT('CLII' AS ticker, 'evgo' AS nombre),
    STRUCT('VERU' AS ticker, 'veru' AS nombre),
    STRUCT('GTT' AS ticker, 'gtt communications' AS nombre),
    STRUCT('DRUG' AS ticker, 'bright minds biosciences' AS nombre),
    STRUCT('CRON' AS ticker, 'cronos' AS nombre),
    STRUCT('CKX' AS ticker, 'ckx lands' AS nombre),
    STRUCT('REGN' AS ticker, 'regeneron pharmaceuticals' AS nombre),
    STRUCT('BTTX' AS ticker, 'better therapeutics' AS nombre),
    STRUCT('NOVN' AS ticker, 'novan' AS nombre),
    STRUCT('GRWG' AS ticker, 'growgeneration' AS nombre),
    STRUCT('BRT' AS ticker, 'brt apartments' AS nombre),
    STRUCT('NSH' AS ticker, 'navsight' AS nombre),
    STRUCT('PB' AS ticker, 'prosperity bancshares' AS nombre),
    STRUCT('BOXL' AS ticker, 'boxlight' AS nombre),
    STRUCT('HOG' AS ticker, 'harley davidson' AS nombre),
    STRUCT('BMTX' AS ticker, 'bm technologies' AS nombre),
    STRUCT('RACE' AS ticker, 'ferrari' AS nombre),
    STRUCT('SRPT' AS ticker, 'sarepta therapeutics' AS nombre),
    STRUCT('MLM' AS ticker, 'martin marietta materials' AS nombre),
    STRUCT('RIME' AS ticker, 'algorhythm' AS nombre),
    STRUCT('NYCB' AS ticker, 'york community bancorp' AS nombre),
    STRUCT('BMNR' AS ticker, 'bitmine immersion technologies, inc. common stock' AS nombre),
    STRUCT('UAMY' AS ticker, 'united states antimony' AS nombre),
    STRUCT('JKS' AS ticker, 'jinkosolar' AS nombre),
    STRUCT('ARBE' AS ticker, 'arbe robotics' AS nombre),
    STRUCT('AUPH' AS ticker, 'aurinia pharmaceuticals' AS nombre),
    STRUCT('CGTX' AS ticker, 'cognition therapeutics' AS nombre),
    STRUCT('RTTR' AS ticker, 'ritter pharmaceuticals' AS nombre),
    STRUCT('APPS' AS ticker, 'digital turbine' AS nombre),
    STRUCT('DMYD' AS ticker, 'dmy technology ii' AS nombre),
    STRUCT('MUDS' AS ticker, 'mudrick capital acq ii' AS nombre),
    STRUCT('BENE' AS ticker, 'benessere capital acquisition' AS nombre),
    STRUCT('GGPI' AS ticker, 'gores guggenheim' AS nombre),
    STRUCT('THBR' AS ticker, 'thunder bridge acq ii' AS nombre),
    STRUCT('ESTC' AS ticker, 'elastic' AS nombre),
    STRUCT('NGAC' AS ticker, 'nextgen acquisition' AS nombre),
    STRUCT('GLND' AS ticker, 'greenland energy' AS nombre),
    STRUCT('SKT' AS ticker, 'tanger factory outlet centers in' AS nombre),
    STRUCT('YCY' AS ticker, 'aa mission acquisition corp. ii class ordinary shares' AS nombre),
    STRUCT('ROCK' AS ticker, 'gibraltar industries' AS nombre),
    STRUCT('TAL' AS ticker, 'tal education' AS nombre),
    STRUCT('UONEK' AS ticker, 'urban one' AS nombre),
    STRUCT('ALJJ' AS ticker, 'alj regional' AS nombre),
    STRUCT('CLDR' AS ticker, 'cloudera' AS nombre),
    STRUCT('ALOT' AS ticker, 'astronova' AS nombre),
    STRUCT('LEGO' AS ticker, 'legato merger corp. iv ordinary shares' AS nombre),
    STRUCT('MEGL' AS ticker, 'magic empire global' AS nombre),
    STRUCT('PENG' AS ticker, 'penguin solutions' AS nombre),
    STRUCT('ATNM' AS ticker, 'actinium pharmaceuticals' AS nombre),
    STRUCT('SUNE' AS ticker, 'sunation energy' AS nombre),
    STRUCT('FAT' AS ticker, 'fat brands' AS nombre),
    STRUCT('PHAT' AS ticker, 'phanthom pharmaceuticals' AS nombre),
    STRUCT('ZSAN' AS ticker, 'zosano pharma' AS nombre),
    STRUCT('IBIO' AS ticker, 'ibio' AS nombre),
    STRUCT('MSAI' AS ticker, 'multisensor ai' AS nombre),
    STRUCT('ASX' AS ticker, 'ase technology' AS nombre),
    STRUCT('SMX' AS ticker, 'smx security matters' AS nombre),
    STRUCT('SMX' AS ticker, 'security matters' AS nombre),
    STRUCT('IPGP' AS ticker, 'ipg photonics' AS nombre),
    STRUCT('AVYA' AS ticker, 'avaya' AS nombre),
    STRUCT('JAN' AS ticker, 'janus living, inc. class a-1 common stock' AS nombre),
    STRUCT('CLSK' AS ticker, 'cleanspark' AS nombre),
    STRUCT('DXYZ' AS ticker, 'destiny tech100' AS nombre),
    STRUCT('PPL' AS ticker, 'ppl corp' AS nombre),
    STRUCT('PPL' AS ticker, 'ppl corporation' AS nombre),
    STRUCT('SWI' AS ticker, 'solarwinds' AS nombre),
    STRUCT('MGNI' AS ticker, 'magnite' AS nombre),
    STRUCT('PXMD' AS ticker, 'paxmedica' AS nombre),
    STRUCT('LUNA' AS ticker, 'luna innovations' AS nombre),
    STRUCT('FRGT' AS ticker, 'freight technologies' AS nombre),
    STRUCT('DARE' AS ticker, 'dare bioscience' AS nombre),
    STRUCT('NVTA' AS ticker, 'invitae' AS nombre),
    STRUCT('SPG' AS ticker, 'simon property' AS nombre),
    STRUCT('SEAS' AS ticker, 'seaworld entertainment' AS nombre),
    STRUCT('KEYS' AS ticker, 'keysight technologies' AS nombre),
    STRUCT('GFAI' AS ticker, 'guardforce ai' AS nombre),
    STRUCT('CIFR' AS ticker, 'cipher mining' AS nombre),
    STRUCT('ARDX' AS ticker, 'ardelyx' AS nombre),
    STRUCT('RIG' AS ticker, 'transocean' AS nombre),
    STRUCT('IINN' AS ticker, 'inspira technologies oxy bhn' AS nombre),
    STRUCT('CRKN' AS ticker, 'crown electrokinetics' AS nombre),
    STRUCT('HUT' AS ticker, 'hut 8' AS nombre),
    STRUCT('ICU' AS ticker, 'seastar medical' AS nombre),
    STRUCT('NWTG' AS ticker, 'newton golf company, inc.' AS nombre),
    STRUCT('CALM' AS ticker, 'cal maine foods' AS nombre),
    STRUCT('KIDS' AS ticker, 'orthopediatrics' AS nombre),
    STRUCT('USAR' AS ticker, 'usa rare earth, inc.' AS nombre),
    STRUCT('WE' AS ticker, 'wework' AS nombre),
    STRUCT('GLSI' AS ticker, 'greenwich lifesciences' AS nombre),
    STRUCT('TOST' AS ticker, 'toast' AS nombre),
    STRUCT('EBET' AS ticker, 'ebet' AS nombre),
    STRUCT('ANF' AS ticker, 'abercrombie & fitch' AS nombre),
    STRUCT('ONTO' AS ticker, 'onto innovation' AS nombre),
    STRUCT('HYMC' AS ticker, 'hycroft mining' AS nombre),
    STRUCT('REKR' AS ticker, 'rekor systems' AS nombre),
    STRUCT('RF' AS ticker, 'regions financial' AS nombre),
    STRUCT('ACEV' AS ticker, 'ace convergence acquisition' AS nombre),
    STRUCT('BTWN' AS ticker, 'bridgetown' AS nombre),
    STRUCT('CNL' AS ticker, 'collective mining' AS nombre),
    STRUCT('ZM' AS ticker, 'zoom communications' AS nombre),
    STRUCT('DAY' AS ticker, 'dayforce' AS nombre),
    STRUCT('CIDM' AS ticker, 'cinedigm' AS nombre),
    STRUCT('AEZS' AS ticker, 'aeterna zentaris' AS nombre),
    STRUCT('XRX' AS ticker, 'xerox' AS nombre),
    STRUCT('NOG' AS ticker, 'northern oil & gas' AS nombre),
    STRUCT('JFK' AS ticker, '8i enterprises acquisition' AS nombre),
    STRUCT('MDWT' AS ticker, 'midwest' AS nombre),
    STRUCT('BMRA' AS ticker, 'biomerica' AS nombre),
    STRUCT('CXAI' AS ticker, 'cxapp' AS nombre),
    STRUCT('ACIC' AS ticker, 'american coastal insurance' AS nombre),
    STRUCT('MIND' AS ticker, 'mind technology' AS nombre),
    STRUCT('FIZZ' AS ticker, 'national beverage' AS nombre),
    STRUCT('PRE' AS ticker, 'prenetics global' AS nombre),
    STRUCT('ALUS' AS ticker, 'alussa energy acquisition' AS nombre),
    STRUCT('GAP' AS ticker, 'gap' AS nombre),
    STRUCT('JWN' AS ticker, 'nordstrom' AS nombre),
    STRUCT('VSPR' AS ticker, 'vesper healthcare acquisition' AS nombre),
    STRUCT('VSPR' AS ticker, 'hydrafacial' AS nombre),
    STRUCT('VSPR' AS ticker, 'beautyhealth' AS nombre),
    STRUCT('HOFV' AS ticker, 'hall of fame resort' AS nombre),
    STRUCT('EH' AS ticker, 'ehang' AS nombre),
    STRUCT('BROS' AS ticker, 'dutch bros' AS nombre),
    STRUCT('LPSN' AS ticker, 'liveperson' AS nombre),
    STRUCT('COMS' AS ticker, 'comsovereign' AS nombre),
    STRUCT('HEXO' AS ticker, 'hexo' AS nombre),
    STRUCT('LILM' AS ticker, 'lilium' AS nombre),
    STRUCT('AMRN' AS ticker, 'amarin' AS nombre),
    STRUCT('CBRS' AS ticker, 'cerebras systems inc.' AS nombre),
    STRUCT('STZ' AS ticker, 'constellation brands' AS nombre),
    STRUCT('LAES' AS ticker, 'sealsq' AS nombre),
    STRUCT('CNSP' AS ticker, 'cns pharmaceuticals' AS nombre),
    STRUCT('INVH' AS ticker, 'invitation homes' AS nombre),
    STRUCT('FB' AS ticker, 'meta platforms' AS nombre),
    STRUCT('TLS' AS ticker, 'telos' AS nombre),
    STRUCT('FCX' AS ticker, 'freeport mcmoran' AS nombre),
    STRUCT('NXTD' AS ticker, 'nxt id' AS nombre),
    STRUCT('EDR' AS ticker, 'endeavor' AS nombre),
    STRUCT('PIXY' AS ticker, 'shiftpixy' AS nombre),
    STRUCT('BTAI' AS ticker, 'bioxcel therapeutics' AS nombre),
    STRUCT('TCDA' AS ticker, 'tricida' AS nombre),
    STRUCT('GIX' AS ticker, 'gigcapital9 corp.' AS nombre),
    STRUCT('BIG' AS ticker, 'big lots' AS nombre),
    STRUCT('SI' AS ticker, 'shoulder innovations, inc. common stock' AS nombre),
    STRUCT('RCKY' AS ticker, 'rocky brands' AS nombre),
    STRUCT('AGM' AS ticker, 'federal agricultural mort' AS nombre),
    STRUCT('GRA' AS ticker, 'wr grace' AS nombre),
    STRUCT('GRA' AS ticker, 'w r grace' AS nombre),
    STRUCT('LZB' AS ticker, 'la-z-boy' AS nombre),
    STRUCT('PTE' AS ticker, 'polarityte' AS nombre),
    STRUCT('ZNTE' AS ticker, 'zanite acquisition' AS nombre),
    STRUCT('RMED' AS ticker, 'ra medical systems' AS nombre),
    STRUCT('HUBC' AS ticker, 'hub cyber security' AS nombre),
    STRUCT('ING' AS ticker, 'ing groep' AS nombre),
    STRUCT('ING' AS ticker, 'ing group' AS nombre),
    STRUCT('CMPS' AS ticker, 'compass pathways' AS nombre),
    STRUCT('TTI' AS ticker, 'tetra technologies' AS nombre),
    STRUCT('MNMD' AS ticker, 'mind medicine mindmed' AS nombre),
    STRUCT('OSS' AS ticker, 'one stop systems' AS nombre),
    STRUCT('KBH' AS ticker, 'kb home' AS nombre),
    STRUCT('OBK' AS ticker, 'origin bancorp' AS nombre),
    STRUCT('FET' AS ticker, 'forum energy technologies' AS nombre),
    STRUCT('SII' AS ticker, 'sprott' AS nombre),
    STRUCT('GTLB' AS ticker, 'gitlab' AS nombre),
    STRUCT('OXM' AS ticker, 'oxford industries' AS nombre),
    STRUCT('MBAC' AS ticker, 'm3 brigade acquisition ii' AS nombre),
    STRUCT('DNUT' AS ticker, 'krispy kreme' AS nombre),
    STRUCT('CVAC' AS ticker, 'curevac' AS nombre),
    STRUCT('CABA' AS ticker, 'cabaletta bio' AS nombre),
    STRUCT('HITI' AS ticker, 'high tide' AS nombre),
    STRUCT('BDRX' AS ticker, 'biodexa pharmaceuticals' AS nombre),
    STRUCT('AACQ' AS ticker, 'artius acquisition' AS nombre),
    STRUCT('UNFI' AS ticker, 'united natural foods' AS nombre),
    STRUCT('APP' AS ticker, 'applovin' AS nombre),
    STRUCT('STEP' AS ticker, 'stepstone' AS nombre),
    STRUCT('CMG' AS ticker, 'chipotle mexican grill' AS nombre),
    STRUCT('THO' AS ticker, 'thor industries' AS nombre),
    STRUCT('MO' AS ticker, 'altria' AS nombre),
    STRUCT('RNG' AS ticker, 'ringcentral' AS nombre),
    STRUCT('JAGX' AS ticker, 'jaguar health' AS nombre),
    STRUCT('AMPX' AS ticker, 'amprius technologies' AS nombre),
    STRUCT('FTHM' AS ticker, 'fathom' AS nombre),
    STRUCT('NBAC' AS ticker, 'newborn acquisition' AS nombre),
    STRUCT('TPET' AS ticker, 'trio petroleum' AS nombre),
    STRUCT('RELI' AS ticker, 'reliance global' AS nombre),
    STRUCT('DOLE' AS ticker, 'dole' AS nombre),
    STRUCT('CRML' AS ticker, 'critical metals' AS nombre),
    STRUCT('OTLY' AS ticker, 'oatly' AS nombre),
    STRUCT('MNLO' AS ticker, 'menlo therapeutics' AS nombre),
    STRUCT('GROW' AS ticker, 'us global investors' AS nombre),
    STRUCT('FLWS' AS ticker, '1-800-flowers' AS nombre),
    STRUCT('FLWS' AS ticker, '1-800 flowers' AS nombre),
    STRUCT('VST' AS ticker, 'vistra' AS nombre),
    STRUCT('JBLU' AS ticker, 'jetblue airways' AS nombre),
    STRUCT('ACTC' AS ticker, 'arclight clean trans' AS nombre),
    STRUCT('GEO' AS ticker, 'geo' AS nombre),
    STRUCT('SNE' AS ticker, 'sony' AS nombre),
    STRUCT('MRVI' AS ticker, 'maravai lifesciences' AS nombre),
    STRUCT('GOGO' AS ticker, 'gogo' AS nombre),
    STRUCT('VIACA' AS ticker, 'viacomcbs' AS nombre),
    STRUCT('VCX' AS ticker, 'fundrise innovation fund, llc common shares of limited liability interests' AS nombre),
    STRUCT('MAX' AS ticker, 'mediaalpha' AS nombre),
    STRUCT('DCAR' AS ticker, 'dropcar' AS nombre),
    STRUCT('BNED' AS ticker, 'barnes & noble education' AS nombre),
    STRUCT('RAVE' AS ticker, 'rave restaurant' AS nombre),
    STRUCT('TRIT' AS ticker, 'triterras' AS nombre),
    STRUCT('ANET' AS ticker, 'arista networks' AS nombre),
    STRUCT('SON' AS ticker, 'sonoco products' AS nombre),
    STRUCT('BTBT' AS ticker, 'bit digital' AS nombre),
    STRUCT('ASTR' AS ticker, 'astra space' AS nombre),
    STRUCT('SMFL' AS ticker, 'smart for life' AS nombre),
    STRUCT('AOS' AS ticker, 'ao smith' AS nombre),
    STRUCT('AOS' AS ticker, 'a.o. smith' AS nombre),
    STRUCT('CBRL' AS ticker, 'cracker barrel old country store' AS nombre),
    STRUCT('AME' AS ticker, 'ametek' AS nombre),
    STRUCT('EVOL' AS ticker, 'evolving systems' AS nombre),
    STRUCT('CHEK' AS ticker, 'check-cap' AS nombre),
    STRUCT('BRC' AS ticker, 'brady' AS nombre),
    STRUCT('SPR' AS ticker, 'spirit aerosystems' AS nombre),
    STRUCT('RBNE' AS ticker, 'robin energy ltd.' AS nombre),
    STRUCT('MIST' AS ticker, 'milestone pharmaceuticals' AS nombre),
    STRUCT('AHT' AS ticker, 'ashford hospitality' AS nombre),
    STRUCT('ROST' AS ticker, 'ross stores' AS nombre),
    STRUCT('FLT' AS ticker, 'fleetcor technologies' AS nombre),
    STRUCT('ACRX' AS ticker, 'acelrx pharmaceuticals' AS nombre),
    STRUCT('CMA' AS ticker, 'comerica' AS nombre),
    STRUCT('LAND' AS ticker, 'gladstone land' AS nombre),
    STRUCT('RUM' AS ticker, 'rumble' AS nombre),
    STRUCT('MITT' AS ticker, 'ag mortgage investment' AS nombre),
    STRUCT('NSC' AS ticker, 'norfolk southern' AS nombre),
    STRUCT('GSX' AS ticker, 'gsx techedu' AS nombre),
    STRUCT('GSX' AS ticker, 'gaotu' AS nombre),
    STRUCT('SPRQ' AS ticker, 'spartan acquisition ii' AS nombre),
    STRUCT('EXE' AS ticker, 'expand energy' AS nombre),
    STRUCT('NP' AS ticker, 'neptune insurance inc. class common stock' AS nombre),
    STRUCT('FRG' AS ticker, 'franchise' AS nombre),
    STRUCT('GREE' AS ticker, 'greenidge generation' AS nombre),
    STRUCT('GENE' AS ticker, 'genetic technologies' AS nombre),
    STRUCT('BCH' AS ticker, 'banco de chile' AS nombre),
    STRUCT('TOWN' AS ticker, 'townebank' AS nombre),
    STRUCT('RXRX' AS ticker, 'recursion pharmaceuticals' AS nombre),
    STRUCT('SXTP' AS ticker, '60 degrees pharmaceuticals' AS nombre),
    STRUCT('SRNG' AS ticker, 'soaring eagle acquisition' AS nombre),
    STRUCT('YAAS' AS ticker, 'youxin technology' AS nombre),
    STRUCT('BRPA' AS ticker, 'big rock partners acquisition' AS nombre),
    STRUCT('BRPA' AS ticker, 'neurorx' AS nombre),
    STRUCT('EVA' AS ticker, 'enviva' AS nombre),
    STRUCT('COO' AS ticker, 'cooper companies' AS nombre),
    STRUCT('CYCU' AS ticker, 'cycurion, inc.' AS nombre),
    STRUCT('NDLS' AS ticker, 'noodles &' AS nombre),
    STRUCT('T' AS ticker, 'at&t' AS nombre),
    STRUCT('WBS' AS ticker, 'webster financial' AS nombre),
    STRUCT('TRIP' AS ticker, 'tripadvisor' AS nombre),
    STRUCT('TMBR' AS ticker, 'timber pharmaceuticals' AS nombre),
    STRUCT('NKLR' AS ticker, 'terra innovatum global n.v.' AS nombre),
    STRUCT('GMHI' AS ticker, 'gores metropoulos' AS nombre),
    STRUCT('UTZ' AS ticker, 'utz brands' AS nombre),
    STRUCT('TYME' AS ticker, 'tyme technologies' AS nombre),
    STRUCT('KIDZ' AS ticker, 'kidz ai inc.' AS nombre),
    STRUCT('H' AS ticker, 'hyatt hotels' AS nombre),
    STRUCT('BOH' AS ticker, 'bank of hawaii' AS nombre),
    STRUCT('HIMX' AS ticker, 'himax technologies' AS nombre),
    STRUCT('TALK' AS ticker, 'talkspace' AS nombre),
    STRUCT('GHVI' AS ticker, 'gores vi' AS nombre),
    STRUCT('BAND' AS ticker, 'bandwidth' AS nombre),
    STRUCT('LTM' AS ticker, 'latam airlines' AS nombre),
    STRUCT('NES' AS ticker, 'nuverra environmental soluts' AS nombre),
    STRUCT('GLXY' AS ticker, 'galaxy digital inc.' AS nombre),
    STRUCT('HSBC' AS ticker, 'hsbc' AS nombre),
    STRUCT('KVUE' AS ticker, 'kenvue' AS nombre),
    STRUCT('DUOL' AS ticker, 'duolingo' AS nombre),
    STRUCT('GHC' AS ticker, 'graham' AS nombre),
    STRUCT('GHM' AS ticker, 'graham' AS nombre),
    STRUCT('SRAC' AS ticker, 'stable road acquisition' AS nombre),
    STRUCT('OPY' AS ticker, 'oppenheimer' AS nombre),
    STRUCT('PACB' AS ticker, 'pacific biosciences calif' AS nombre),
    STRUCT('BNAI' AS ticker, 'brand engagement network' AS nombre),
    STRUCT('AXDX' AS ticker, 'accelerate diagnostics' AS nombre),
    STRUCT('TRVG' AS ticker, 'trivago' AS nombre),
    STRUCT('GES' AS ticker, 'guess' AS nombre),
    STRUCT('NIU' AS ticker, 'niu technologies' AS nombre),
    STRUCT('SUMO' AS ticker, 'sumo logic' AS nombre),
    STRUCT('INDO' AS ticker, 'indonesia energy' AS nombre),
    STRUCT('INTU' AS ticker, 'intuit' AS nombre),
    STRUCT('CMCSA' AS ticker, 'comcast' AS nombre),
    STRUCT('AYX' AS ticker, 'alteryx' AS nombre),
    STRUCT('MOVE' AS ticker, 'movano' AS nombre),
    STRUCT('SPLK' AS ticker, 'splunk' AS nombre),
    STRUCT('SLDP' AS ticker, 'solid power' AS nombre),
    STRUCT('PUBM' AS ticker, 'pubmatic' AS nombre),
    STRUCT('JACK' AS ticker, 'jack in box' AS nombre),
    STRUCT('WWR' AS ticker, 'westwater resources' AS nombre),
    STRUCT('IOVA' AS ticker, 'iovance biotherapeutics' AS nombre),
    STRUCT('CODX' AS ticker, 'co-diagnostics' AS nombre),
    STRUCT('VERB' AS ticker, 'verb technology' AS nombre),
    STRUCT('CCAQ' AS ticker, 'collective acquisition corp.' AS nombre),
    STRUCT('SMR' AS ticker, 'nuscale power' AS nombre),
    STRUCT('MA' AS ticker, 'mastercard' AS nombre),
    STRUCT('STPK' AS ticker, 'star peak energy transition' AS nombre),
    STRUCT('GRPN' AS ticker, 'groupon' AS nombre),
    STRUCT('AGBA' AS ticker, 'agba group' AS nombre),
    STRUCT('AGBA' AS ticker, 'agba' AS nombre),
    STRUCT('FOX' AS ticker, 'fox' AS nombre),
    STRUCT('X' AS ticker, 'united states steel' AS nombre),
    STRUCT('BIOC' AS ticker, 'biocept' AS nombre),
    STRUCT('HIHO' AS ticker, 'highway' AS nombre),
    STRUCT('FGL' AS ticker, 'founder' AS nombre),
    STRUCT('KO' AS ticker, 'coca cola' AS nombre),
    STRUCT('KPLT' AS ticker, 'katapult' AS nombre),
    STRUCT('VLTA' AS ticker, 'volta' AS nombre),
    STRUCT('KELYA' AS ticker, 'kelly services' AS nombre),
    STRUCT('KELYB' AS ticker, 'kelly services' AS nombre),
    STRUCT('GOED' AS ticker, '1847 goedeker' AS nombre),
    STRUCT('LOW' AS ticker, 'lowes companies' AS nombre),
    STRUCT('HLT' AS ticker, 'hilton worldwide' AS nombre),
    STRUCT('EDU' AS ticker, 'oriental educ & tech gp' AS nombre),
    STRUCT('SKM' AS ticker, 'sk telecom' AS nombre),
    STRUCT('LIDR' AS ticker, 'aeye' AS nombre),
    STRUCT('SERV' AS ticker, 'serve robotics' AS nombre),
    STRUCT('ENDP' AS ticker, 'endo international' AS nombre),
    STRUCT('PIPP' AS ticker, 'pine island acquisition' AS nombre),
    STRUCT('BOXD' AS ticker, 'boxed' AS nombre),
    STRUCT('MBOT' AS ticker, 'microbot medical' AS nombre),
    STRUCT('TTNP' AS ticker, 'titan pharmaceuticals' AS nombre),
    STRUCT('DDS' AS ticker, 'dillards' AS nombre),
    STRUCT('TIO' AS ticker, 'tingo' AS nombre),
    STRUCT('KTRA' AS ticker, 'kintara therapeutics' AS nombre),
    STRUCT('NERV' AS ticker, 'minerva neurosciences' AS nombre),
    STRUCT('SFT' AS ticker, 'shift technologies' AS nombre),
    STRUCT('JCS' AS ticker, 'communications systems' AS nombre),
    STRUCT('SBAC' AS ticker, 'sba communications' AS nombre),
    STRUCT('SBFM' AS ticker, 'sunshine biopharma' AS nombre),
    STRUCT('ISIG' AS ticker, 'insignia systems' AS nombre),
    STRUCT('VAL' AS ticker, 'valaris' AS nombre)
  ])
),
gkg AS (
  SELECT
    CAST(SUBSTR(CAST(DATE AS STRING), 1, 8) AS INT64) AS dia,
    LOWER(V2Organizations) AS orgs,
    CAST(SPLIT(V2Tone, ',')[OFFSET(0)] AS FLOAT64) AS tono
  FROM `gdelt-bq.gdeltv2.gkg_partitioned`
  WHERE _PARTITIONTIME >= TIMESTAMP('2020-01-01')
    AND _PARTITIONTIME <  TIMESTAMP('2026-07-01')
    AND V2Themes LIKE '%ECON_STOCKMARKET%'
    AND V2Organizations IS NOT NULL AND V2Organizations != ''
)
SELECT
  e.ticker,
  g.dia,
  COUNT(*) AS articulos,
  ROUND(AVG(g.tono), 4) AS tono
FROM gkg g
JOIN entidades e
  ON STRPOS(g.orgs, e.nombre) > 0
GROUP BY e.ticker, g.dia
ORDER BY e.ticker, g.dia;
